title: 书籍原始标题
target_title: 书籍翻译后的标题
author: 作者名
google_api_key: 你的Google API密钥
model: gemini-2.5-pro-preview-03-25 or gemini-2.5-flash-preview-04-17
target_language: 中文
source_language: 英文
s3_access_key_id: 你的S3访问密钥ID
s3_secret_access_key: 你的S3访问密钥
s3_bucket_name: 你的S3存储桶名称
s3_endpoint: 你的S3端点URL
num_retries: 3  # API调用失败时的重试次数
max_backoff_seconds: 30  # 重试时的最大退避时间（秒）
previous_content_limit: 0  # 设置翻译时使用的前文上下文字符数（0表示不使用上下文，可减少Token消耗）
max_continuation_attempts: 3  # HTML响应不完整时的最大继续尝试次数
