title: 感傷マゾvol2
target_title: 感傷マゾ
author: 感傷マゾ
google_api_key: AIzaSyBvtQ1B0GN0ckQILx-1L-qdG-m_73owtdM
model: gemini-2.5-pro-preview-03-25
target_language: 中文
source_language: 英文
s3_access_key_id: 00609f70e6bf72c0000000001
s3_secret_access_key: K006h0v8NVUKoNW4z+fFH1kFGNoo3ig
s3_bucket_name: translator233
s3_endpoint: http://s3.ca-east-006.backblazeb2.com/
num_retries: 3  
max_backoff_seconds: 30  
previous_content_limit: 0  
max_continuation_attempts: 3  
