title: 感傷マゾvol2
target_title: 感伤受虐2
author: A
google_api_key: AIzaSyBvtQ1B0GN0ckQILx-1L-qdG-m_73owtdM
model: gemini-2.5-pro-preview-03-25
target_language: 中文
source_language: 日文
s3_access_key_id: 00609f70e6bf72c0000000002
s3_secret_access_key: K0065fXdButzMqVZ72K777DYu5F445M
s3_bucket_name: translator233
s3_endpoint: https://s3.ca-east-006.backblazeb2.com
num_retries: 3  
max_backoff_seconds: 30  
previous_content_limit: 0  
max_continuation_attempts: 3  
